name: Build Wallet

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: gvenzl/oracle-xe:21

    steps:
      - name: Work in progress
        run: pwd && ls && whoami && echo Hello, world!
      
