name: Build Wallet

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: gvenzl/oracle-xe:21

    steps:
      - name: Create temp folder
        run: mkdir -p /tmp/wallet-build && cd /tmp/wallet-build
      - name: Create new wallet
        run:  orapki wallet create -wallet tmp_wallet -pwd 'Pass_123' -auto_login
      - name: Download Amazon bundle
        run: pwd && curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -o global-bundle.pem
      - name: List files
        run: ls -lah
      - name: Extract certs from Amazon global bundle and add those to the wallet
        run: |
           csplit global-bundle.pem '/-----BEGIN CERTIFICATE-----/' '{*}' && rm xx00
           find . -name 'xx*' -type f -exec orapki wallet add -wallet tmp_wallet -trusted_cert -cert {} -pwd 'Pass_123' \;    
           rm xx*
      - name: Extract certs from Mozilla CA bundle and add those to the wallet
        run: |
           csplit /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem '/-----BEGIN CERTIFICATE-----/' '{*}' && rm xx00
           find . -name 'xx*' -type f -exec orapki wallet add -wallet tmp_wallet -trusted_cert -cert {} -pwd 'Pass_123' \;    
           rm xx*
      - name: List files
        run: ls -lah
                  
