name: Build Wallet

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: gvenzl/oracle-xe:21

    steps:
      - name: Work in progress
        run: pwd && ls && whoami && echo Hello, world!
      - name: Download Amazon bundle
        run: curl https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem -O global-bundle.pem
      - name: Build a wallet
        run: |
           csplit global-bundle.pem '/-----BEGIN CERTIFICATE-----/' '{*}'
           orapki wallet create -wallet tmp_wallet -pwd 'Pass_123' -auto_login
           find . -name 'xx*' -type f -exec orapki wallet add -wallet tmp_wallet -trusted_cert -cert {} -pwd 'Pass_123' \;          
